### ISSUE TITLE
Mejora de ENDES.PE

### ISSUE THREAD

**Issue by horaciochacon** [horaciochacon/ENDES.PE#2]
@avallecam 

He hecho bastantes cambios a lo largo de todo el paquete, ahora además tiene 0 errores en CMD Check. Algo que me di cuenta es que usando codificación latin1 no aparecen esos errores de tipo ivalid bytestring y aparecen "ñ" y "tildes" al mostrar la info en la consola, me hace pensar si podría ponerlo como default.

También modifiqué los vignettes, aunque aquí faltan unos cuantos ajustes. Dale una mirada a todo cuando tengas tiempo para asegurar que mis cambios no rompieron nada. 

Saludos

**Comment by avallecam** [comment]
@horaciochacon 

- ¿Qué opinas sobre mencionar en el README que también se puede realizar lo mismo con la ENAHO? Podría complementar con un segundo vignette solamente con ENAHO, para mostrar ejemplos de la función `consulta_enaho` y `archivos_*`

- Tengo una nueva función para la descarga de varios años, la cual conserva los argumentos de `consulta_*` y enmascara `purrr::pmap`. Luego de probar la actualización haré el pull request para que la veas. El segundo vignette podría ser excusa para mostrarla también.

**Comment by horaciochacon** [comment]
@avallecam 

Me gusta mucho la idea de todo lo que estás planteando, estas semanas serán un poco pesadas para mí pero si añades algunos pull request puedo darle una revisada. 

Definitivamente hay varias cosas para probar y optimizar. 

Gracias por la colaboración!
